### ISSUE TITLE
release planning for 0.9

### ISSUE THREAD

**Issue by FelixSchwarz** [FelixSchwarz/mjml-python#39]
@caseyjhol: Is there anything else you would like to add to this repo soon-ish or should we rename the repo and release 0.9? 
I remember you were working on a different css inlining mechanism.

No hurry from my side but it might be nice to release all the work you did so far.

**Comment by caseyjhol** [comment]
I have been working on migrating to premailer (because of this issue: https://github.com/Stranger6667/css-inline/issues/185). However, some other things took priority, so not sure when I'll be able to get back to that, so it might be good to do another release now since there are a lot of new features now.

I'll push my changes up and open a WIP PR for the premailer stuff, and you could maybe tackle the last few items if you get a chance?

**Comment by FelixSchwarz** [comment]
Ok, so I released mjml 0.9.

I'm currently very short on time (sorry for the late reviews) but hopefully I can return to more mjml later this year. Thanks for publishing your code which can provide a good starting point.
